version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    networks:
      - elastic-network
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "ELASTIC_PASSWORD"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    networks:
      - elastic-network
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SA_PASSWORD"
      ACCEPT_EULA: "Y"

networks:
  elastic-network:
    driver: bridge