version: '3'

services:
  elastic-embeddings:
    build: .
    networks:
      - elastic-embeddings-network
    ports:
      - "8080:8080"
    volumes:
      - ./src/ElasticEmbeddings.API/Data:/app/Data
    env_file:
      - .env
    depends_on:
      elasticsearch:
        condition: service_healthy
        
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    networks:
      - elastic-embeddings-network
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "ELASTIC_PASSWORD"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --user elastic:ELASTIC_PASSWORD --insecure -XGET https://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 2s
      timeout: 10s
      retries: 30

networks:
  elastic-embeddings-network:
    driver: bridge